from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .types import MarketContext, SourcePlan, market_dir_slug

_HEADER = (
    "# GENERATED by the market-first discovery pipeline -- REVIEW BEFORE USE.\n"
    "# Generated from the durable market context (rule text pinned by SHA-256 at\n"
    "# context-build time; execution fails closed if Polymarket edits the rules).\n"
    "# The operator gate still applies: dry_run stays true and the position mode\n"
    "# stays alert_only until the standard inspect/preflight/ack sequence is run.\n"
)


def emit_bot_config(context: MarketContext, plan: SourcePlan, *, entry_usd: float, out_path: Path, ledger_path: str = "") -> Path:
    """Render a ready-to-review executor config for this market: the existing
    entry/defense/exit engines are the final execution component, so the
    pipeline's output is their input format. When `ledger_path` is given, the
    config binds the executor to the shared portfolio ledger so live fills
    debit the same budgets the pipeline allocates against."""
    if context.rule_analysis is None:
        raise ValueError(f"market {context.market_id} has no rule analysis; refusing to emit an executor config")
    if plan.rule_text_sha256 != context.rule_text_sha256:
        raise ValueError(f"source plan for {context.market_id} was built for a different rule-text version; rebuild it")
    if context.kind == "grouped":
        payload = _location_config(context, plan, entry_usd)
    else:
        payload = _binary_config(context, plan, entry_usd)
    if ledger_path:
        payload["portfolio"] = {
            "ledger_path": ledger_path,
            "market_id": context.market_id,
            "event_slug": context.event_slug,
            "correlation_group": context.correlation_group or "uncategorized",
            "deadline_iso": context.deadline_iso,
        }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8")
    return out_path


def _binary_config(context: MarketContext, plan: SourcePlan, entry_usd: float) -> dict[str, Any]:
    outcome = context.outcomes[0]
    return {
        "market": {
            "slug": context.event_slug,
            "question": outcome.question or context.question,
            "expected_question_contains": (outcome.question or context.question)[:60],
            "deadline_date": _date_only(context.deadline_iso),
            "held_side": "",
            "expected_rule_text_sha256": context.rule_text_sha256,
            "resolution_rules": context.rule_text,
        },
        "position": {
            "expected_yes_token_id": outcome.yes_token_id,
            "expected_no_token_id": outcome.no_token_id,
        },
        "entry": {"enabled": True, "side": "YES", "usd_budget": entry_usd, "max_price": 0.90, "max_entries": 1},
        "classifier": {"provider": "anthropic", "model": "claude-opus-4-8", "passes": 2, "require_pass_agreement": True},
        "execution": {"dry_run": True, "sell": {"enabled": True, "min_price": 0.03}, "flip_buy": {"enabled": False}},
        "keywords": {"escalate_terms": plan.escalate_terms},
        "safety": {"one_shot": True, "max_executions": 2, "poll_seconds": 30.0},
        "sources": _sources_section(plan),
        "data_dir": f"data/geopolitics/{_slug(context.market_id)}",
        "logs_dir": "logs",
    }


def _location_config(context: MarketContext, plan: SourcePlan, entry_usd: float) -> dict[str, Any]:
    return {
        "event": {
            "slug": context.event_slug,
            "question": context.question,
            "deadline_date": _date_only(context.deadline_iso),
            "held_location": "",
            "expected_rule_text_sha256": context.rule_text_sha256,
            "resolution_rules": context.rule_text,
        },
        "outcomes": [
            {
                "name": o.name,
                "label": o.label,
                "condition_id": o.condition_id,
                "yes_token_id": o.yes_token_id,
                "no_token_id": o.no_token_id,
                "rotation_target": False,
            }
            for o in context.outcomes
        ],
        "entry": {
            "enabled": True,
            # Every configured leg is enterable on a tier-one confirmation;
            # the operator should trim this list during review.
            "targets": [o.name for o in context.outcomes],
            "usd_budget": entry_usd,
            "max_price": 0.90,
            "max_entries": 1,
        },
        "classifier": {"provider": "anthropic", "model": "claude-opus-4-8", "passes": 2, "require_pass_agreement": True},
        "execution": {"dry_run": True, "sell": {"enabled": True, "min_price": 0.03}, "buy_rotation": {"enabled": False}},
        "safety": {"one_shot": True, "max_executions": 2, "poll_seconds": 30.0},
        "sources": {**_sources_section(plan), "feed_include_terms": plan.escalate_terms},
        "data_dir": f"data/geopolitics/{_slug(context.market_id)}",
        "logs_dir": "logs",
    }


def _sources_section(plan: SourcePlan) -> dict[str, Any]:
    return {
        "poll_urls": list(plan.poll_urls),
        "feed_urls": list(plan.feed_urls),
        "auto_trade_domains": list(plan.auto_trade_domains),
        "alert_only_domains": list(plan.alert_only_domains),
        "allow_feed_auto_trade": False,
        "max_trade_article_age_hours": 24.0,
    }


def _date_only(deadline_iso: str) -> str:
    return (deadline_iso or "").strip()[:10]


def _slug(market_id: str) -> str:
    return market_dir_slug(market_id)
